version: "3.9"

services:
  db:
    volumes:
      - postgres_data::/var/lib/postgresql/data

    image: postgres
    container_name: django_container
    user: postgres
    environment:
        POSTGRES_NAME: postgres
        POSTGRES_USER: django_user
        POSTGRES_PASSWORD: 123456789
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: web_container
    command: python /news_site/manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: postgres
      DATABASE_USER: django_user
      DATABASE_PASSWORD: 123456789
      DATABASE_URL: postgres://django_user:123456789@db/tms_django

volumes:
      postgres_data:





