# Generated by Django 4.2.6 on 2023-11-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0003_article_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "article",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content",
                        to="news_app.article",
                    ),
                ),
            ],
        ),
    ]
