# Generated by Django 4.2.6 on 2023-11-01 20:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0004_remove_article_content_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="content",
            new_name="story",
        ),
    ]
