# Generated by Django 4.2.6 on 2023-11-06 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0013_alter_article_slug_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"default_related_name": "categories"},
        ),
    ]
