# Generated by Django 4.2.6 on 2023-11-06 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("news_app", "0014_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"default_related_name": "articles"},
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="news_app.category"
            ),
        ),
    ]
