# Generated by Django 4.2.6 on 2023-11-06 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0016_comment_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='update',
        ),
    ]
