# Generated by Django 4.2.6 on 2023-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0017_remove_comment_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='likes',
        ),
    ]
