# Generated by Django 4.2.6 on 2023-11-12 14:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("news_app", "0020_comment_likes_delete_likecomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="user",
            field=models.ManyToManyField(
                related_name="favourite_art", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
